name: Build and Push to DigitalOcean

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to DigitalOcean Container Registry
      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DOCR_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCR_ACCESS_TOKEN }}" --password-stdin registry.digitalocean.com

          
      # Step 3: Pull the existing image (if it exists)
      - name: Pull Existing Image
        run: |
          docker pull registry.digitalocean.com/powerup/powerup:frontend-prod || echo "No existing latest tag found"

      # Step 4: Remove Existing Tag
      - name: Remove Existing Tag
        run: |
          docker rmi registry.digitalocean.com/powerup/powerup:frontend-prod || echo "No existing latest tag to remove"

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t registry.digitalocean.com/powerup/powerup:frontend-prod .

      # Step 6: Push the Docker image
      - name: Push Docker image
        run: |
          docker push registry.digitalocean.com/powerup/powerup:frontend-prod
